# Generated by Django 5.0.7 on 2024-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionarena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='product_src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
